services:
  directus:
    image: directus/directus:11.17.2
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      SECRET: ${DIRECTUS_SECRET}
      PUBLIC_URL: ${PUBLIC_URL:-http://localhost:8055}
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: ${FRAME_SRC:-localhost:3000}
    ports:
      - "8055:8055"
    volumes:
      - ./uploads:/directus/uploads
