services:
  directus:
    image: directus/directus:11.9.0
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: localhost:3000
    ports:
      - "8055:8055"
